In [7]:
from transformers import GPT2TokenizerFast
from transformers import AutoModelForCausalLM
import pickle
import numpy as np
# Initialize tokenizer and model
model_name ="DeepESP/gpt2-spanish"
#n_features = 768

tokenizer = GPT2TokenizerFast.from_pretrained(model_name, add_prefix_space=True, cache_dir = "/data/u_barchet_software/cache/")
model = AutoModelForCausalLM.from_pretrained(model_name, cache_dir = "/data/u_barchet_software/cache/")

# Print out model architecture
model.eval()

Loading weights: 100%|██████████| 149/149 [00:00<00:00, 26459.68it/s]
[transformers] GPT2LMHeadModel LOAD REPORT from: DeepESP/gpt2-spanish
Key                                     | Status     |  | 
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True, bias=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [ ]:
import pandas as pd

events_meg = pd.read_csv("../brain2qwerty/SpanishBCBL/Pinet2024Meg/events.csv")

In [31]:
events_perception = events_meg[(events_meg['is_percep'] == True) & (events_meg['type'] == "Word")]
events_perception = events_perception[['type', 'start', 'stop', 'subject', 'session', 'task', 'text', 'trial_id', 'true_sequence']]

events_perception = events_perception[events_perception['trial_id'] > 3]

In [32]:
sentences_uni = events_perception['true_sequence'].unique()
sentences_ids = pd.DataFrame(zip(sentences_uni, range(len(sentences_uni))), columns = ['true_sequence', 'sid'])

events_perception_id = pd.merge(events_perception, sentences_ids, on = "true_sequence")

In [ ]:
unique_df = events_perception_id[['sid', 'text']].drop_duplicates().reset_index(drop=True)

In [ ]:
import pandas as pd
from textgrid import TextGrid
import torch
import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
from accelerate import Accelerator

from os import listdir
from os.path import isfile, join


ids = unique_df


emb_all = []
for sid in unique_df['sid'].unique():

    df = unique_df[unique_df['sid'] == sid]
    
    
    
    df['word_number'] = range(1, len(df) + 1)

    
    # Initialize tokenizer and model
    model_name = "DeepESP/gpt2-spanish"
    
    device = "cpu"
    model.to(device)
    
    
    
    # Reload in transcript CSV file
    transcript_gpt2 = df.copy()
    
    # Insert explicit index column for reference
    transcript_gpt2.insert(0, 'word_index', transcript_gpt2.index.values)
    
    # Tokenize words into lists of tokens
    transcript_gpt2['token'] = transcript_gpt2.text.apply(tokenizer.tokenize)
    
    # "Explode" lists of token subwords into long format
    transcript_gpt2 = transcript_gpt2.explode('token', ignore_index=True)
    
    # Convert tokens to token IDs for input to model
    transcript_gpt2['token_id'] = transcript_gpt2.token.apply(tokenizer.convert_tokens_to_ids)


    
    
    # Convert all token IDs into list
    token_ids = transcript_gpt2.token_id.tolist()
    
    # Extract context window width for model
    max_len = 100
    
    # Compile into lists of tokens within each context window
    samples = []
    token_ids = torch.tensor(transcript_gpt2.token_id.tolist(), dtype=torch.long)
    samples.append(token_ids[0:max_len])
    for i in range(max_len+1, len(token_ids)+1):
        samples.append(token_ids[i-max_len:i])
    

    # Initialize accelerator and free memory
    accelerator = Accelerator()
    accelerator.free_memory()
    
    # Send model to device
    model = model.to(device)
    

    # Set a batch size for the data loader
    batch_size = 4
    
    # Extract a late-intermediate layer from GPT-2
    layer = 8
    
    # Extract embeddings and other model features
    embeddings = []
    top_guesses = []
    ranks = []
    true_probs = []
    entropies = []
    with torch.no_grad():
        data_loader = torch.utils.data.DataLoader(samples, batch_size=batch_size,
                                                  shuffle=False)
    
        # Loop through samples and extract embeddings
        for i, batch in enumerate(tqdm(data_loader)):
            output = model(batch.to(device), output_hidden_states=True)
            logits = output.logits  # torch.Size([2, 1024, 50257])
            states = output.hidden_states[layer]
    
            # Extract all embeddings/features for first context window
            if i == 0:
                true_ids = batch[0, :]
                brange = list(range(len(true_ids)-1))
                logits_order = logits[0].argsort(descending=True, dim=-1)
                batch_top_guesses = logits_order[:-1, 0]
                print(batch_top_guesses)
                batch_ranks = torch.eq(logits_order[:-1],
                                       true_ids.reshape(-1,1)[1:].to(device)).nonzero()[:, 1]
                batch_probs = logits[0, :-1].softmax(-1)
                batch_true_probs = batch_probs[brange, true_ids[1:]]

                batch_entropy = torch.distributions.Categorical(
                    logits=logits[0, :-1].float()
                ).entropy()

               # batch_entropy = torch.distributions.Categorical(probs=batch_probs).entropy()
                batch_embeddings = states[0]
    
                top_guesses.append(batch_top_guesses.numpy(force=True))
                ranks.append(batch_ranks.numpy(force=True))
                true_probs.append(batch_true_probs.numpy(force=True))
                entropies.append(batch_entropy.numpy(force=True))
                embeddings.append(batch_embeddings.numpy(force=True))
                
                # Reset if there are samples remaining in this batch
                if batch.size(0) == 1:
                    continue
                logits = logits[1:]
                states = states[1:]
                batch = batch[1:]
    
            # Extract embeddings/features for last word in subsequent windows
            true_ids = batch[:, -1]
            brange = list(range(len(true_ids)))
            logits_order = logits[:, -2, :].argsort(descending=True)  # batch x vocab_size
            batch_top_guesses = logits_order[:, 0]
            batch_ranks = torch.eq(logits_order, true_ids.reshape(-1,1).to(device)).nonzero()[:, 1]
            batch_probs = torch.softmax(logits[:, -2, :], dim=-1)
            batch_true_probs = batch_probs[brange, true_ids]
            batch_entropy = torch.distributions.Categorical(probs=batch_probs).entropy()
            batch_embeddings = states[:, -1, :]

            print(batch_top_guesses)

            top_guesses.append(batch_top_guesses.numpy(force=True))
            ranks.append(batch_ranks.numpy(force=True))
            true_probs.append(batch_true_probs.numpy(force=True))
            entropies.append(batch_entropy.numpy(force=True))
            embeddings.append(batch_embeddings.numpy(force=True))

                # Compile outputs into transcript (logit derivatives must be shifted by 1)
    transcript_gpt2.loc[1:, 'rank'] = np.concatenate(ranks)
    transcript_gpt2.loc[1:, 'true_prob'] = np.concatenate(true_probs)
    transcript_gpt2.loc[1:, 'top_pred'] = np.concatenate(top_guesses)
    transcript_gpt2.loc[0, 'top_pred'] = tokenizer.bos_token_id
    transcript_gpt2.loc[1:, 'entropy'] = np.concatenate(entropies)
    transcript_gpt2['embedding'] = [e for e in np.vstack(embeddings)]
    
    # Reduce size of transcript
    transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',
                                          'rank': 'float32', 'true_prob': 'float32',
                                          'top_pred': 'int32', 'entropy': 'float32', 
                                             }, copy=False)
    
    # Convert model's top predictions from token IDs to tokens
    transcript_gpt2['top_pred'] = transcript_gpt2.top_pred.apply(tokenizer.convert_ids_to_tokens)
    
    # Print out top-1 and top-10 word prediction accuracy
    print(f"Top-1 accuracy: {(transcript_gpt2['rank'] == 0).mean():.3f}")
    print(f"Top-10 accuracy: {(transcript_gpt2['rank'] < 10).mean():.3f}")
    
    mean_embeddings = (
        transcript_gpt2.groupby('word_number', as_index=False)
          .agg({
              'embedding': lambda x: np.mean(np.stack(x), axis=0),
              'text': 'first',
            'word_index': 'first',
    
              
              'sid':'first'
          })
        )

    emb_all.append(mean_embeddings)



  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  329,  268, 4505,  329,   23,  288, 1817,  393])


100%|██████████| 1/1 [00:03<00:00,  3.14s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.100
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626,   333,   297,  1238, 19442,   494,   268, 12710,  1860,  4489])


100%|██████████| 1/1 [00:04<00:00,  4.67s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.364


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  275,   23,   21,  268, 2427])


100%|██████████| 1/1 [00:02<00:00,  2.41s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,  1005,   268,   335, 14469,    21,   457,   335,  3121,  5741])


100%|██████████| 1/1 [00:04<00:00,  4.67s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.182
Top-10 accuracy: 0.545


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,    23,   299, 12048,   268,   338,   637])


100%|██████████| 1/1 [00:02<00:00,  2.68s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.375


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  602,   23,  288, 4016])


100%|██████████| 1/1 [00:02<00:00,  2.12s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  335, 6558,  268,  297])


100%|██████████| 1/1 [00:02<00:00,  2.37s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  281, 2901,  324,  288, 2404])


100%|██████████| 1/1 [00:02<00:00,  2.62s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.125
Top-10 accuracy: 0.500


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  457,  402,  288,  398])


100%|██████████| 1/1 [00:02<00:00,  2.40s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.143


100%|██████████| 1/1 [00:02<00:00,  2.37s/it]

tensor([1626,  268,  288, 5940, 4796,  268])
Top-1 accuracy: 0.000
Top-10 accuracy: 0.143



/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',
  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23, 2120, 7765,  268,  288])


100%|██████████| 1/1 [00:02<00:00,  2.43s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.429


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,   268,   363,  3121,   762, 32203])


100%|██████████| 1/1 [00:02<00:00,  2.39s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.143


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626,   268,   288, 22841,   268,   297])


100%|██████████| 1/1 [00:02<00:00,  2.52s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626,   268,    23, 30699,   268])


100%|██████████| 1/1 [00:02<00:00,  2.25s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  299, 1542,  307,  299, 1076])


100%|██████████| 1/1 [00:02<00:00,  2.40s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.143


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238, 3139,  268,  299, 4297, 2763,  268,  335, 9164])


100%|██████████| 1/1 [00:03<00:00,  3.08s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.300
Top-10 accuracy: 0.300


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,   268, 10911,  1740,  3633,   288, 10575])


100%|██████████| 1/1 [00:02<00:00,  2.56s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.125
Top-10 accuracy: 0.500


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  281, 2219,  802,  808,  288, 1561])


100%|██████████| 1/1 [00:02<00:00,  2.64s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.125
Top-10 accuracy: 0.250


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,  1296,   745,    23,   584,   278,    23,  1739,  1487, 23854])


100%|██████████| 1/1 [00:05<00:00,  5.14s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.182
Top-10 accuracy: 0.455


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   268,   299,  2096,   268,   297, 15878])


100%|██████████| 1/1 [00:02<00:00,  2.65s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.500


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238, 1491,   35, 6122,  268])


100%|██████████| 1/1 [00:02<00:00,  2.17s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,  363, 4105,  490, 1014])


100%|██████████| 1/1 [00:02<00:00,  2.40s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.143


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,   23,  363, 3430])


100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,  363, 1958,  268])


100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,   268,   420,   277,   307, 14752])


100%|██████████| 1/1 [00:02<00:00,  2.48s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.286
Top-10 accuracy: 0.429


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   268,   363, 23631,    21,   299,  1526,  1281])


100%|██████████| 1/1 [00:02<00:00,  2.82s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.111
Top-10 accuracy: 0.222


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  299, 9547,  325, 6718,  268, 1858,  462])


100%|██████████| 1/1 [00:02<00:00,  2.73s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.111
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  268,  281, 4070,  633,  726])


100%|██████████| 1/1 [00:02<00:00,  2.47s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  312,   21, 4876,  268,  335])


100%|██████████| 1/1 [00:02<00:00,  2.47s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.143


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,   268,   363,  6672,   268, 11778,   745])


100%|██████████| 1/1 [00:02<00:00,  2.69s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.125
Top-10 accuracy: 0.375


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  268,  335,  637,  268,  363])


100%|██████████| 1/1 [00:02<00:00,  2.45s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.286
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  933, 1074,  268,  299,  859,  268])


100%|██████████| 1/1 [00:02<00:00,  2.67s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.250


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,   23,  297, 1955])


100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  465,  370,  268])


100%|██████████| 1/1 [00:02<00:00,  2.20s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  288, 8729, 1407,  268,  304, 3733,  285])


100%|██████████| 1/1 [00:03<00:00,  3.06s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.100
Top-10 accuracy: 0.500


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  297,  859,  268,  299, 4363, 6314, 5741])


100%|██████████| 1/1 [00:03<00:00,  3.07s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238, 7399,  382, 1074, 6388,  303, 1445,   21])


100%|██████████| 1/1 [00:02<00:00,  2.75s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.111
Top-10 accuracy: 0.222


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  268,  288])


100%|██████████| 1/1 [00:02<00:00,  2.04s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,    23, 22604,    21,   297,  4708,   339])


100%|██████████| 1/1 [00:02<00:00,  2.71s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.125


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  288, 3535, 4805, 1003,  306,  304, 6728])


100%|██████████| 1/1 [00:03<00:00,  3.02s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.300
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,    21,   288,   324, 13653,  7918])


100%|██████████| 1/1 [00:02<00:00,  2.47s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268, 1548,   21,  299, 3275,  343])


100%|██████████| 1/1 [00:02<00:00,  2.72s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.375


100%|██████████| 1/1 [00:04<00:00,  4.76s/it]

tensor([ 1563,   324,   577,   304,  1681,   887,   514,   335,  3334, 16746])



/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.182
Top-10 accuracy: 0.364


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  297,  278,  324,  865])


100%|██████████| 1/1 [00:02<00:00,  2.48s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.286
Top-10 accuracy: 0.429


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  268,  268,  329,  288])


100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  297, 1563,  268, 3577,  297, 4119])


100%|██████████| 1/1 [00:02<00:00,  2.91s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.111
Top-10 accuracy: 0.444


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,   23, 3633,  885])


100%|██████████| 1/1 [00:02<00:00,  2.40s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268, 2238,  268,  288,  859])


100%|██████████| 1/1 [00:02<00:00,  2.67s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   268, 45837,   288,  2901,   268,  1140,  1199])


100%|██████████| 1/1 [00:02<00:00,  2.90s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   397,  1122,   268,   288,  3463, 15851,   473])


100%|██████████| 1/1 [00:02<00:00,  2.79s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.333
Top-10 accuracy: 0.444


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   268,  6617, 15257,    23,   297,  2253])


100%|██████████| 1/1 [00:02<00:00,  2.65s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.125


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,   268,  3562,  3585, 16448,   268,   297])


100%|██████████| 1/1 [00:02<00:00,  2.68s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.125
Top-10 accuracy: 0.125


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,   23,   88,   23,  288, 3362])


100%|██████████| 1/1 [00:02<00:00,  2.45s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  307, 4831,  268])


100%|██████████| 1/1 [00:02<00:00,  2.22s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  596,  297, 9162,  348,  268,  297, 2238])


100%|██████████| 1/1 [00:02<00:00,  2.93s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.111
Top-10 accuracy: 0.556


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268, 1046,  374, 1010,  268,  288, 3362])


100%|██████████| 1/1 [00:02<00:00,  2.87s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.222
Top-10 accuracy: 0.444


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,   21,  288,  268, 3064])


100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  299,  268, 3692, 6672])


100%|██████████| 1/1 [00:02<00:00,  2.48s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.143


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  268, 4134,  268,  463, 2275,   94])


100%|██████████| 1/1 [00:02<00:00,  2.89s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  307,  304, 4297, 4413,  297, 4122])


100%|██████████| 1/1 [00:02<00:00,  2.71s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.125
Top-10 accuracy: 0.250


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,   23,  268,  299,   35,  288,  557,  419])


100%|██████████| 1/1 [00:02<00:00,  2.87s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.111
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  288, 1563,  268, 1626])


100%|██████████| 1/1 [00:02<00:00,  2.54s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626,   268,   307, 14752])


100%|██████████| 1/1 [00:02<00:00,  2.10s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626,   268,   297,  6980, 15522,  1600])


100%|██████████| 1/1 [00:02<00:00,  2.50s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.429


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   268,   363, 17002,  9515])


100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  397, 1122,  268,  473,  954])


100%|██████████| 1/1 [00:02<00:00,  2.48s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.429


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  299,  288, 8093])


100%|██████████| 1/1 [00:02<00:00,  2.07s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  297])


100%|██████████| 1/1 [00:01<00:00,  1.84s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  288, 8729, 1407])


100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  288,  637])


100%|██████████| 1/1 [00:02<00:00,  2.04s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   268, 13608,   281,  1114])


100%|██████████| 1/1 [00:02<00:00,  2.29s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   324, 13561,   304,  4821])


100%|██████████| 1/1 [00:02<00:00,  2.28s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.167


100%|██████████| 1/1 [00:02<00:00,  2.12s/it]

tensor([1626,  268,  299, 3275,  343])
Top-1 accuracy: 0.000
Top-10 accuracy: 0.333



/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',
100%|██████████| 1/1 [00:02<00:00,  2.17s/it]

tensor([1114,  268,  363, 1487, 6755])



/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,  363, 4297])


100%|██████████| 1/1 [00:02<00:00,  2.12s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  299])


100%|██████████| 1/1 [00:01<00:00,  1.95s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626,   268,   288, 14339])


100%|██████████| 1/1 [00:02<00:00,  2.03s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   268,   299, 11031])


100%|██████████| 1/1 [00:02<00:00,  2.02s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,   23,   88,  288, 3362])


100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1114,   280,    21,   577,   288, 12963,   343])


100%|██████████| 1/1 [00:02<00:00,  2.62s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.250
Top-10 accuracy: 0.375


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  299, 9619])


100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114, 1957,   23,  307,  637])


100%|██████████| 1/1 [00:02<00:00,  2.19s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  268, 4134])


100%|██████████| 1/1 [00:01<00:00,  1.99s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563, 1005,  268,  584,  281, 3121, 5741])


100%|██████████| 1/1 [00:02<00:00,  2.60s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.500


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,  299, 2203])


100%|██████████| 1/1 [00:02<00:00,  2.03s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  281, 9402])


100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  299, 1074, 1561])


100%|██████████| 1/1 [00:01<00:00,  1.96s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   268, 21537,   288])


100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563, 16395,   268,   288,  5500])


100%|██████████| 1/1 [00:02<00:00,  2.26s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   268, 45837,   288,  5667])


100%|██████████| 1/1 [00:02<00:00,  2.15s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  307, 4831])


100%|██████████| 1/1 [00:01<00:00,  1.99s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  370])


100%|██████████| 1/1 [00:01<00:00,  1.86s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  288,  859])


100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  297,  278])


100%|██████████| 1/1 [00:02<00:00,  2.03s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,  297, 4998])


100%|██████████| 1/1 [00:02<00:00,  2.07s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  281, 2219,  808,  288, 4413])


100%|██████████| 1/1 [00:02<00:00,  2.49s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.286


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268, 3577,  297, 4119])


100%|██████████| 1/1 [00:02<00:00,  2.30s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.500


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114, 6556,  268,   23, 9276])


100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   596,   297, 11850])


100%|██████████| 1/1 [00:02<00:00,  2.07s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268, 1173, 6516])


100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.400


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563, 17742,   268,   761,   288,  1573])


100%|██████████| 1/1 [00:02<00:00,  2.45s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.429


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,  268,  299, 2096])


100%|██████████| 1/1 [00:01<00:00,  2.00s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  297, 6509])


100%|██████████| 1/1 [00:02<00:00,  2.02s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  288, 5940, 4796])


100%|██████████| 1/1 [00:02<00:00,  2.41s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  370, 3385])


100%|██████████| 1/1 [00:02<00:00,  2.03s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,   21,  288])


100%|██████████| 1/1 [00:01<00:00,  1.86s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  363, 1487])


100%|██████████| 1/1 [00:02<00:00,  2.07s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


100%|██████████| 1/1 [00:01<00:00,  1.98s/it]

tensor([1238, 2333,   23,  363])



/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1563,   268, 15216,   299])


100%|██████████| 1/1 [00:02<00:00,  2.02s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1626, 29459,    79,   268, 39686])


100%|██████████| 1/1 [00:02<00:00,  2.24s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23,  297, 4021, 3885])


100%|██████████| 1/1 [00:02<00:00,  2.27s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.167
Top-10 accuracy: 0.333


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268, 3633,  289])


100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  299,  859])


100%|██████████| 1/1 [00:02<00:00,  2.00s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238,   21,  297, 7918])


100%|██████████| 1/1 [00:02<00:00,  2.05s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  288,  398])


100%|██████████| 1/1 [00:02<00:00,  2.08s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  363, 3121,  762])


100%|██████████| 1/1 [00:02<00:00,  2.18s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.167


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  363, 3893])


100%|██████████| 1/1 [00:02<00:00,  2.03s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,   23, 2120])


100%|██████████| 1/1 [00:01<00:00,  1.79s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.250


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1114,  268,  288, 1563])


100%|██████████| 1/1 [00:02<00:00,  2.02s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1563,  268,  297])


100%|██████████| 1/1 [00:01<00:00,  1.81s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.000


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1238, 3139,  268,  299, 4297, 2763])


100%|██████████| 1/1 [00:02<00:00,  2.39s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.143
Top-10 accuracy: 0.143


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  306,  304])


100%|██████████| 1/1 [00:02<00:00,  2.07s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.200
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([1626,  268,  297, 7765])


100%|██████████| 1/1 [00:02<00:00,  2.08s/it]
/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


Top-1 accuracy: 0.000
Top-10 accuracy: 0.200


  0%|          | 0/1 [00:00<?, ?it/s]

tensor([ 1238,   268,  1826,   335, 24685])


100%|██████████| 1/1 [00:02<00:00,  2.16s/it]

Top-1 accuracy: 0.000
Top-10 accuracy: 0.333



/tmp/ipykernel_27783/2041811967.py:156: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  transcript_gpt2 = transcript_gpt2.astype({'word_index': 'int32', 'token_id': 'int32',


In [ ]:
with open("./embeddings/embeddings_gpt.pickle", "wb") as o:
    pickle.dump(emb_all, o)